# Site settings
title: Gabriele Sarti - Home
description: Gabriele Sarti's Personal Portfolio

# User settings
username: Gabriele Sarti
user_description: 
user_title: Software Developer
email: anon@anon.com
github_username:  gsarti

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
