# Site settings
title: Gabriele Sarti
description: Gabriele Sarti's Personal Portfolio

# User settings
username: Gabriele Sarti
user_title: Software Developer
email: gabriele.sarti996@gmail.com
github_username:  gsarti

# Google-analytics
google-analytics:
  id: "105332518"

exclude: ['package.json', 'src' , 'node_modules']
